<template>
    <div class="grid grid-cols-1 lg:grid-cols-[2fr_8fr]">
        <!-- Sidebar -->
        <div class="w-full lg:shadow-lg sticky top-0 z-10 left-0 lg:shadow-gray-400 gap-4 bg-white flex flex-start sm:items-center flex-col sm:flex-row lg:flex-col justify-between p-6 lg:h-screen">
            <div class="flex flex-col items-start sm:flex-row lg:flex-col lg:items-start sm:items-center">
                <div>
                    <img class="w-36 lg:w-52" src="../assets/codenicely_name_w_small@2x 1.jpg" alt="">
                </div>
                <div class="flex flex-col sm:flex-row lg:flex-col gap-2 items-start">
                    <button class="w-full text-start py-3 font-semibold px-2">Team</button>
                    <button class="bg-blue-600 px-2 py-3 text-white font-semibold text-start w-full">Invoice</button>
                </div>
            </div>

            <div class="w-fit lg:w-full">
                <button class="logout-btn w-full" @click="handleLogout">Logout</button>
            </div>
        </div>

        <!-- Invoice Lists & Steps -->
        <div class="">
            <div v-if="currentStep >= 1 && currentStep <= 3"
                class="p-3 flex items-center gap-2 bg-white lg:shadow-2xl lg:shadow-gray-400">
                <v-icon @click="handleCurrentBackStep">mdi-arrow-left</v-icon>
                <p>Add New Invoice</p>
            </div>

            <div v-if="currentStep === 0">
                <div class="p-3 flex justify-between bg-white items-center shadow shadow-gray-400">
                    <h2>Invoice List</h2>
                    <div class="border border-gray-950 p-1 rounded-2xl">
                        <v-icon class="text-gray-600 px-4">mdi-magnify</v-icon>
                        <input type="text" class="focus:outline-none" placeholder="Search" name="" id="">
                    </div>
                </div>
                <div class="p-2 flex justify-between items-center">
                    <div class="border border-gray-400 w-fit py-1 rounded-lg px-2">
                        <select class="bg-transparent focus:outline-none lg:px-4" name="Generated by Filter" id="">
                            <option value="Generated by Filter">Generated by Filter</option>
                            <option value="Select 1">Select 1</option>
                            <option value="Select 2">Select 2</option>
                            <option value="Select 3">Select 3</option>
                        </select>
                        <!-- <v-icon>mdi-chevron-down</v-icon> -->
                    </div>
                    <div>
                        <button @click="handleCreateInvoice" class="px-4 py-2 bg-blue-500 rounded-xl text-white">Create
                            Invoice</button>
                    </div>
                </div>

                <!-- Invoice Summary -->
                <div>
                    <div class="grid grid-cols-3 content-center w-full">
                        <div class="border border-gray-400 shadow-sm shadow-gray-300 bg-blue-600 px-2 py-6">
                            <h2>100</h2>
                            <p>Total</p>
                        </div>
                        <div class="border border-gray-400 shadow-sm shadow-gray-300 px-2 py-6">
                            <h2>100</h2>
                            <p>User Generated</p>
                        </div>
                        <div class="border border-gray-400 shadow-sm shadow-gray-300 px-2 py-6">
                            <h2>100</h2>
                            <p>Panel Generated</p>
                        </div>
                    </div>
                </div>

                <!-- Invoice List -->
                <div v-if="invoices.length">
                    <div v-for="invoice in invoices" :key="invoice.id" class="border p-4 my-2 shadow-sm">
                        <h3>Invoice #{{ invoice.invoiceNumber }}</h3>
                        <p><strong>Company:</strong> {{ invoice.companyData.companyName }}</p>
                        <p><strong>User:</strong> {{ invoice.userData.userName }}</p>
                        <p><strong>Total:</strong> ₹{{ invoice.totalAmount }}</p>
                    </div>
                </div>
            </div>

            <!-- Steps for Invoice Creation -->
            <div>
                <CompanyDetails v-if="currentStep === 1" :getCompanyAndUserData="getCompanyAndUserData"
                    :currentStep="currentStep" :updateCurrentStep="updateCurrentStep" />
                <TransactionDetails v-if="currentStep === 2" :handleCurrentBackStep="handleCurrentBackStep"
                    :getTransactioData="getTransactioData" :currentStep="currentStep"
                    :updateCurrentStep="updateCurrentStep" />
                <FinalDetails v-if="currentStep === 3" :handleCurrentBackStep="handleCurrentBackStep"
                    :userData="userData" :companyData="companyData" :transactionData="transactionData"
                    :currentStep="currentStep" @invoiceCreated="resetStep" />
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios';
import CompanyDetails from './CompanyDetails.vue';
import FinalDetails from './FinalDetails.vue';
import TransactionDetails from './TransactionDetails.vue';

export default {
    name: "Invoice",
    components: {
        CompanyDetails, TransactionDetails, FinalDetails
    },
    data() {
        return {
            currentStep: 0,
            beforeCreateInvoice: true,
            userData: {},
            afterFirstStep: true,
            companyData: {},
            transactionData: [],
            invoices: []
        }
    },
    methods: {
        // Get company and user data
        getCompanyAndUserData(company, user) {
            this.companyData = company;
            this.userData = user;
        },

        // Move to the next step
        updateCurrentStep() {
            if (this.currentStep < 3) {
                this.currentStep++;
            }
        },

        resetStep() {
            this.currentStep = 0; // Reset step to 0
        },


        // Start invoice creation
        handleCreateInvoice() {
            if (this.currentStep < 1) {
                this.currentStep = 1;
            }
        },

        // Go back to the previous step
        handleCurrentBackStep() {
            if (this.currentStep >= 1 && this.currentStep <= 3) {
                this.currentStep--;
            }
        },

        // Get transaction data
        getTransactioData(trdata) {
            this.transactionData = trdata;
        },

        // Fetch all invoices from the backend
        async fetchInvoices() {
            try {
                const response = await axios.get("https://node-backend-446i.onrender.com/get-all-data", { withCredentials: true });
                this.invoices = response.data.data;
                console.log("invoice data", this.invoices);

            } catch (error) {
                console.error("Error fetching invoices:", error);
            }
        },

        // Handle logout
        async handleLogout() {
            try {
                const response = await axios.post(
                    "https://node-backend-446i.onrender.com/auth/logout",
                    {},
                    { withCredentials: true }
                );

                if (response.status === 200) {
                    this.$router.push('/');
                }
            } catch (error) {
                console.error("Logout failed:", error);
            }
        }
    },
    mounted() {
        this.fetchInvoices();
    }
}
</script>