<template>
    <div class="grid grid-cols-[2fr_8fr]">
        <div class="shadow-lg sticky top-0 left-0 shadow-gray-400 bg-white p-6 grid grid-cols-1 grid-rows-2 h-screen">
            <div>
                <div>
                    <img src="../assets/codenicely_name_w_small@2x 1.jpg" alt="">
                </div>
                <div class="flex flex-col gap-2 items-start">
                    <button>Team</button>
                    <button>Invoice</button>
                </div>
            </div>

            <div class="content-center">
                <button @click="handleLogout" class="border-2 border-red-700">Logout</button>
            </div>
        </div>

        <!-- Invoice Lists -->
        <div class="">
            <div v-if="currentStep >= 1 && currentStep <= 3"
                class="p-3 flex items-center gap-2 bg-white shadow-2xl shadow-gray-400">
                <v-icon @click="handleCurrentBackStep">mdi-arrow-left</v-icon>
                <p>Add New Invoice</p>
            </div>
            <div v-if="currentStep === 0">
                <div class="p-3 flex justify-between bg-white items-center shadow shadow-gray-400">
                    <h2>Invoice List</h2>
                    <div class="border border-gray-950 p-1 rounded-2xl">
                        <v-icon class="text-gray-600 px-4">mdi-magnify</v-icon>
                        <input type="text" class="focus:outline-none" placeholder="search" name="" id="">
                    </div>
                </div>
                <div class="p-4 flex justify-between items-center">
                    <div class="border border-gray-400 w-fit py-1 rounded-lg px-2">
                        <select class="focus:outline-none px-6" name="Generated by Filter" id="">
                            <option value="Generated by Filter">Generated by Filter</option>
                            <option value="Select 1">Select 1</option>
                            <option value="Select 2">Select 1</option>
                            <option value="Select 3">Select 1</option>
                        </select>
                        <v-icon>mdi-chevron-down</v-icon>
                    </div>
                    <div>
                        <button @click="handleCreateInvoice" class="px-4 py-2 bg-blue-500 rounded-xl text-white">Create
                            Invoice</button>
                    </div>
                </div>
                <div>
                    <div class="grid grid-cols-3 content-center w-full">
                        <div class="border border-gray-400 shadow-sm shadow-gray-300 bg-blue-600 px-2 py-6">
                            <h2>100</h2>
                            <p>Total</p>
                        </div>
                        <div class="border border-gray-400 shadow-sm shadow-gray-300 px-2 py-6">
                            <h2>100</h2>
                            <p>User Generated</p>
                        </div>
                        <div class="border border-gray-400 shadow-sm shadow-gray-300 px-2 py-6">
                            <h2>100</h2>
                            <p>Pannel Genereted</p>
                        </div>
                    </div>
                    <div> </div>
                </div>
            </div>


            <div class="">
                <CompanyDetails v-if="currentStep === 1" :getCompanyAndUserData="getCompanyAndUserData"
                    :currentStep="currentStep" :updateCurrentStep="updateCurrentStep" />
                <TransactionDetails v-if="currentStep === 2" :handleCurrentBackStep="handleCurrentBackStep"
                    :getTransactioData="getTransactioData" :currentStep="currentStep"
                    :updateCurrentStep="updateCurrentStep" />
                <FinalDetails v-if="currentStep === 3" :handleCurrentBackStep="handleCurrentBackStep"
                    :userData="userData" :companyData="companyData" :transactionData="transactionData"
                    :currentStep="currentStep" />
            </div>
            <p>{{ currentStep }}</p>
            <p>{{ beforeCreateInvoice }}</p>
        </div>
    </div>
</template>

<script>
import axios from 'axios';
import CompanyDetails from './CompanyDetails.vue';
import FinalDetails from './FinalDetails.vue';
import TransactionDetails from './TransactionDetails.vue';

export default {
    name: "Invoice",
    components: {
        CompanyDetails, TransactionDetails, FinalDetails
    },
    data() {
        return {
            // createInvoice: false,
            currentStep: 0,
            beforeCreateInvoice: true,
            userData: {},
            afterFirstStep: true,
            companyData: {},
            transactionData: [],
            finalData: ""
        }
    },
    methods: {
        getCompanyAndUserData(company, user) {
            this.companyData = company
            this.userData = user
        },
        updateCurrentStep() {
            if (this.currentStep < 3) {
                this.currentStep = this.currentStep + 1
            }
        },
        handleCreateInvoice() {
            if (this.currentStep < 1) {
                this.currentStep = this.currentStep + 1
            }
        },

        handleCurrentBackStep() {
            if (this.currentStep >= 1 && this.currentStep <= 3) {
                this.currentStep = this.currentStep - 1
            }
        },
        getTransactioData(trdata) {
            this.transactionData = trdata
        },
        async handleLogout() {
            try {
                const response = await axios.post(
                    "http://localhost:8000/auth/logout",
                    {},
                    { withCredentials: true } 
                );

                console.log(response);

                if (response.status === 200) {
                    this.$router.push('/');
                }
                
            } catch (error) {
                console.error("Logout failed:", error);
            }
        }

    }
}
</script>